---
output:
  html_document: default
  word_document: default
---
```{r}
library(tidyverse)
library(broom)
library(rsample)
library(MASS)
# Importing X data
getwd()
setwd('G:/Sunil Files/Softwarica/Asignment/STAT')
X=read.csv(file="X_1.csv",header = F)
colnames(X)= c("X1","X2","X3","X4")


# Importing Y data
Y=read.csv(file="y_1.csv",header = F)
colnames(Y)=c("Y")

# Importing Time data
Ti = read.csv("time_1.csv", header = F)
colnames(Ti)= c('Time')

#Combining all in a Data frame
data_frame= cbind(Ti,X,Y)

#Defining the value of X and Y against time for time series plot.
X.ts=ts(X,start = c(min(Ti),max(Ti)),frequency =1)
Y.ts=ts(Y,start = c(min(Ti),max(Ti)),frequency =1)

#Task 1: Plotting those graphs
plot(X.ts,main = "Time Series Plot of X Signal", xlab = "Time", ylab = "Input Signal")
plot(Y.ts,main = "Time Series Plot of Y Signal", xlab = "Time", ylab = "Output Signal")
```


```{r}
##Task 1.2: Distribution for each EEG signal
#Creating a density if X signal


dis=density(as.matrix(X))
plot(dis,main = "Density plot of whole input signal")
# Creating a Histogram of X signal
hist(as.matrix(X),freq = FALSE,main = "Histogram of signal X ")
#Adding density in the histogram
lines(dis,lwd=2,col="blue")

#Plotting Histogram and density line
#Four plot in a same page
opt = par(mfrow = c(2,2))  

#Creating a density if X1 signal
dis_X1=density(X[,"X1"])
hist(X[,"X1"],freq = FALSE,main = "Signal X1",xlab = "X1 Signal")
lines(dis_X1,lwd=2,col="blue")


#Creating a density if X2 signal
dis_X2=density(X[,"X2"])
hist(X[,"X2"],freq = FALSE,main = "Signal X2",xlab = "X2 Signal")
lines(dis_X2,lwd=2,col="blue")



#Creating a density if X3 signal
dis_X3=density(X[,"X3"])
hist(X[,"X3"],freq = FALSE,main = "Signal  X3",xlab = "X3 Signal")
lines(dis_X3,lwd=2,col="blue")



#Creating a density if X3 signal
dis_X4=density(X[,"X4"])
hist(X[,"X4"],freq = FALSE,main = "Signal X4",xlab = "X4 Signal")
lines(dis_X1,lwd=2,col="blue")
par(opt)

#Creating a density if Y signal
dis_y=density(as.matrix(Y))
plot(dis_y,main = "Density plot of Y",xlab = "Output Signal")
hist(as.matrix(Y),freq = FALSE,main = "Histogram and density plot of Y",xlab = "Output Signal")
lines(dis_y,lwd=2,col="blue")
```

```{r}
## Task 1.3: Creating Correlation and Scatter plot.

# Checking for Correlation OF X1 and Y
cor(data_frame$X1, data_frame$Y)

# Plotting X1 against Y
plot(data_frame$X1, data_frame$Y,main = "Scatter plot between X1 and Y signal", xlab = "X1 signal", ylab = "Output signal" )

# Checking for Correlation OF X2 and Y
cor(data_frame$X2, data_frame$Y)

# Plotting X2 against Y
plot(data_frame$X2, data_frame$Y,main = "Scatter plot between X2 and Y signal", xlab = "X2 signal", ylab = "Output
signal")

# Checking for Correlation OF X3 and Y
cor(data_frame$X3, data_frame$Y)

# Plotting X3 against Y
plot(data_frame$X3, data_frame$Y,main = "Scatter plot between X3 and Y signal", xlab = "X3 signal", ylab = "Output
signal")

# Checking for Correlation OF X4 and Y
cor(data_frame$X4, data_frame$Y)

# Plotting X4 against Y
plot(data_frame$X4, data_frame$Y,main = "Scatter plot between X4 and Y signal", xlab = "X4 signal", ylab = "Output
signal")



```


```{r}
#Task 2 
#First model
first_model <- lm ( Y ~ I(X4) + I(X1^2) + I(X1^3) + I(X2^4) + I(X1^4), data = data_frame)
first_model$coefficients

#Second model
second_model <- lm ( Y ~ I(X4) + I(X1^3) + I(X3^4), data = data_frame)
second_model$coefficients

#Third model
third_model <- lm ( Y ~ I(X3^3) + I(X3^4), data = data_frame)
third_model$coefficients

#Forth model
fourth_model <- lm(Y ~ I(X2) + I(X1^3) + I(X3^4), data = data_frame)
fourth_model$coefficients


#Fifth model
fifth_model <- lm (Y ~ X4 + I(X1^2)+ I (X1^3) + I (X3^4), data = data_frame)
fifth_model$coefficients

#Task 2.2 Residual error
#Residual error of first model
sum(first_model$residuals^2)

#Residual error of Second model
sum(second_model$residuals^2)

#Residual error of Third model
sum(third_model$residuals^2)

#Residual error of Fourth model
sum(fourth_model$residuals^2)

#Residual error of Fifth model
sum(fifth_model$residuals^2)


#Task 2.3 and 2.4 
#Log likelihood function, AIC and  BIC of First model
glance(first_model)

#Log likelihood function of AIC and  BIC Second model
glance(second_model)

#Log likelihood function of AIC and  BIC Third model
glance(third_model)

#Log likelihood function of AIC and  BIC Fourth model
glance(fourth_model)

#Log likelihood function of AIC and  BIC Fifth model
glance(fifth_model)

#Task 2.5: Q-Q Plot
#For First model
plot(first_model, which=2)

#For Second model
plot(second_model, which=2)

#For Third model
plot(third_model, which=2)

#For Forth model
plot(fourth_model, which=2)

#For Fifth model
plot(fifth_model, which=2)

#Task 2.6
# Second model is the best 
# AIC of Second model is -332.6514
# Bic of Second model is -316.1349

#Task 2.7
#Splitting the data set into train and test data set
#Task 2.7.0: splitting 70% to train and 30% to test
#Splitting the data set randomly 
set.seed(123)
dfs=initial_split(data_frame,prop = .7)
dfstrain=training(dfs)
dfstest=testing(dfs)

#Training data from training data set
trfirst_model= lm(Y ~ I(X4) + I(X1^3)  + I(X3^4), data = dfstrain)
glance(trfirst_model)

#Task 2.7.1Predicting form the test data 
predictY=predict(trfirst_model,dfstest)

#Adding the predicted data in test data frame
dfstest["P"]=predictY

#Task 2.7.2:
view(dfstest)

#Mean square error
mean((dfstest$P-dfstest$Y)^2)

#Plotting scatter plot of Test data and Predicted data
plot(dfstest$P,dfstest$Y,xlab = "Actual Test Data",ylab = "Predicted Data")
abline(lm(dfstest$P~dfstest$Y))

#T-test with 95% confident level
tt=t.test(dfstest$Y,dfstest$P,mu=0,alt="two.sided",conf=.95)
tt

#Plot of Confident level 
dis1=density(dfstest$P)
plot(dis1,main = ("Distribution of testing Y data with 95% confidence intervals"))
abline(v=tt$conf.int[1],col =  "blue")
abline(v=tt$conf.int[2], col="red")
```


```{r}
#Task 3:
#Selecting two largest parameters with largest absolute value
PD = c(second_model$coefficients)
sorted_PD = sort(abs(PD), decreasing=TRUE)
sorted_PD

#Choosing parameters
A = sorted_PD[1] 
B = sorted_PD[2]

#Remaining parameter be Constant parameter
C =  sorted_PD[3]  
D = sorted_PD[4]

#Calculating RSS 
RSSmodel = sum(second_model$residuals^2)

#Creating simulated parameter
ni= 100 
counter = 0

#Creating model to get to fit the simulated and constant parameters 
ABCX=cbind(1,(X[,"X4"]),(X[,"X1"])^3,(X[,"X3"])^4)
arr1=0
arr2=0
#Task 3.2:
#Running for loop to generate the simulated numbers
for (i in 1:ni) {
range1 <- runif(1,-A,A) 
range2 <- runif(1,-B,B)
New_X = matrix(c(range1,range2,C,D))
New_Y =     ABCX %*% New_X

# Calculating new RSS value
new_RSS <- sum((Y - New_Y)^2) 

#Task 3.3:
#Comparing simulated data for real data 
if (new_RSS > RSSmodel){
arr1[i] = range1 
arr2[i] = range2 
counter = counter+1


  } #Closing else loop
} #Closing for loop

#Task 3.4
hist(arr1)
hist(arr2)
plot(arr1,arr2)

```

